# Pengaturan Situs Web

# Impor tema
theme: jekyll-theme-chirpy

# Bahasa situs › https://www.w3.org/International/questions/qa-choosing-language-tags
# Jika file dengan nama yang sama ada di folder `_data/locales`, maka bahasa tata letak akan berubah,
# jika tidak, bahasa tata letak akan menggunakan nilai default 'en'.
lang: id

# Ubah ke zona waktu Anda › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Jakarta

# Pengaturan jekyll-seo-tag › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Ricaldocs # Judul utama

tagline: Unfiltered Tech Library # Subjudul

description: >- # Digunakan oleh seo meta dan atom feed
  Ricaldocs menyajikan tutorial, dokumentasi IT, dan artikel opini seputar Privacy, Cybersecurity, Cloud Computing, serta IT Infrastructure. Ditulis oleh Risnanda Pascal, platform open source ini berfokus pada kemandirian digital, privasi pengguna, dan kontrol penuh atas data. Jelajahi panduan langkah demi langkah, analisis tren teknologi terkini, dan berkontribusi dalam membangun ekosistem pengetahuan yang terpercaya.

# Isi dengan protokol dan domain situs web Anda.
# Contoh, 'https://username.github.io', pastikan tidak diakhiri dengan '/'.
url: "https://docs.ricalnet.my.id"

github:
  username: ricaldocs # Nama pengguna Github

twitter:
  username: # Nama pengguna Twitter

social:
  # Ubah ke nama lengkap Anda.
  # Ini akan ditampilkan sebagai penulis default untuk posting dan pemilik hak cipta di footer
  name: Ricalnet
  email: ricalnet@duck.com # Alamat email
  links:
    # Tautan pertama akan menjadi tautan untuk pemilik hak cipta
    - https://ricalnet.my.id/
    - https://github.com/ricaldocs # Beranda Github
    - https://twitter.com/ # Beranda Twitter
    # Hapus komentar untuk menambahkan lebih banyak tautan
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Pengaturan verifikasi situs web
webmaster_verifications:
  google: NiiRcCxWZldJCJ4K7AqkQ6Pb28Lp0hQ0SMkfUM2QlSY
  bing: 6BCB568EB23B07CD7EAEC4F8A9A3FDD7
  alexa: # Masukkan kode verifikasi Alexa Anda
  yandex: # Masukkan kode verifikasi Yandex Anda
  baidu: # Masukkan kode verifikasi Baidu Anda
  facebook: # Masukkan kode verifikasi Facebook Anda

# ↑ --------------------------
# Akhir pengaturan `jekyll-seo-tag`

# Pengaturan analitik web
analytics:
  google:
    id: # Masukkan ID Google Analytics Anda
  goatcounter:
    id: # Masukkan ID GoatCounter Anda
  umami:
    id: # Masukkan ID Umami Anda
    domain: # Masukkan domain Umami Anda
  matomo:
    id: # Masukkan ID Matomo Anda
    domain: # Masukkan domain Matomo Anda
  cloudflare:
    id: # Masukkan token Cloudflare Web Analytics Anda
  fathom:
    id: # Masukkan Fathom Site ID Anda

# Pengaturan jumlah tampilan halaman
pageviews:
  provider: # Saat ini hanya mendukung 'goatcounter'

# Atur skema warna preferensi
#
# Petunjuk: Biarkan kosong akan mengikuti preferensi warna default sistem, dan di bagian bawah bilah samping akan muncul
# tombol untuk beralih antara tema terang dan gelap.
#
# Opsi yang tersedia:
#
#     light  - Gunakan skema terang
#     dark   - Gunakan skema gelap
#
theme_mode: # [light | dark]

# Aktifkan efek animasi latar belakang
backgroud_animation: true

# Aktifkan efek klik mouse
mouse_click_effect: false

# Titik akhir CDN aset media.
# Perhatikan bahwa setelah ditetapkan, URL CDN akan ditambahkan ke
# semua jalur aset media (avatar situs, gambar dalam posting, file audio dan video) yang dimulai dengan '/'
#
# Contoh, 'https://cdn.com'
cdn: ""

# Avatar di bilah samping, mendukung sumber lokal atau CROS
avatar: /avatar.jpg

# URL gambar pratinjau sosial situs-wide yang digunakan dalam tag meta SEO `og:image`.
# Dapat diganti dengan `page.image` di Front Matter posting.
social_preview_image: # String, sumber lokal atau lintas domain

# Atur konten yang ditampilkan di bilah sisi kanan
panel:
  # Atur konten yang ditampilkan di bilah sisi kanan dalam posting
  #
  # Petunjuk:
  #   Jika sakelar global false, blok terkait pasti tidak akan ditampilkan.
  #   Jika sakelar global true, dapat dinonaktifkan untuk posting tertentu di header file md posting dengan format:
  #      lastmod: false
  post:
    # Pembaruan terakhir
    lastmod: false
    # Tag tren
    trending_tags: false
    # Tautan eksternal
    external_links: true
    # Daftar isi
    toc: true

comments:
  # Sakelar global untuk bagian komentar posting, misalnya, 'disqus'. Biarkan kosong untuk menonaktifkan.
  provider: # [disqus | utterances | giscus]
  # Opsi provider dapat sebagai berikut:
  # Sistem komentar disqus > https://disqus.com/
  disqus:
    shortname: # Masukkan disqus shorname Anda › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # Sistem komentar utterances › https://utteranc.es/
  utterances:
    repo: # <Nama pengguna Github>/<Nama repositori>
    issue_term: # < url | pathname | title | ...>
  # Sistem komentar Waline › https://waline.js.org/
  waline:
    server: # Alamat server Vercal
    placeholder: Say something! # Teks yang ditampilkan saat kotak komentar kosong
    avatar: mp # Avatar default › https://waline.js.org/guide/client/avatar.html
  # Opsi Giscus › https://giscus.app
  giscus:
    repo: # <Nama pengguna Github>/<Nama repositori>
    repo_id:
    category:
    category_id:
    mapping: # Opsional, default adalah 'pathname'
    strict: # Opsional, default adalah '0'
    input_position: # Opsional, default adalah 'bottom'
    lang: # Opsional, default adalah nilai `site.lang`
    reactions_enabled: # Opsional, default adalah 1

# Aset statik yang di-host sendiri, opsional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true # AKTIFKAN self-host untuk semua aset statis
    # Tentukan lingkungan Jekyll, kosongkan berarti diaktifkan untuk semua
    # Hanya berlaku jika `assets.self_host.enabled` adalah 'true'
    env: # [development|production] - Biarkan kosong untuk semua environment

pwa:
  enabled: true # Opsi fitur PWA (dapat diinstal)
  cache:
    enabled: true # Opsi cache offline PWA
    # Tentukan path yang tidak akan di-cache oleh PWA di sini.
    # Biasanya nilainya adalah `baseurl` dari situs web lain yang menggunakan domain yang sama dengan situs saat ini.
    deny_paths:
      # - "/example"  # URL yang cocok dengan `<SITE_URL>/example/*` tidak akan di-cache oleh PWA

# Jumlah posting per halaman
paginate: 10

# URL dasar situs
baseurl: ""

# ------------ Pengaturan di bawah ini tidak disarankan untuk diubah ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Pengaturan Rouge › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # String kosong berarti semua file dalam proyek
      type: posts
    values:
      layout: post
      comments: true # Aktifkan komentar di posting
      # Tampilan default bilah sisi kanan
      lastmod: false
      trending_tags: true
      external_links: true
      toc: true
      license: true
      # Jangan ubah ini kecuali Anda adalah ahli dalam Jekyll dan pengembangan Web,
      # atau Anda merasa cukup pintar untuk memodifikasi ke path relatif lain dalam template ini.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # Lihat `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
