services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:Z
      - bundle_gems:/usr/local/bundle:Z
    restart: unless-stopped
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling"

    cpus: 0.5
    mem_limit: 512M
    mem_reservation: 256M

volumes:
  bundle_gems:
